data_dir: D:/shinyi/datamining/kaggle-child-mind-institute-detect-sleep-states/data
processed_dir: D:/shinyi/datamining/kaggle-child-mind-institute-detect-sleep-states/processed_data
output_dir: D:/shinyi/datamining/kaggle-child-mind-institute-detect-sleep-states/data/output
model_dir: D:/shinyi/datamining/kaggle-child-mind-institute-detect-sleep-states/data/output/train
sub_dir: D:/shinyi/datamining/kaggle-child-mind-institute-detect-sleep-states/data/output/submission